"""Add updated roles

Revision ID: 0ea2b9ba687e
Revises: 8a77bd9a7112
Create Date: 2023-06-03 23:09:26.147842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea2b9ba687e'
down_revision = '8a77bd9a7112'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
