"""Add final updated roles

Revision ID: 16b130af7813
Revises: 0ea2b9ba687e
Create Date: 2023-06-04 17:44:41.665314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b130af7813'
down_revision = '0ea2b9ba687e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
