"""Add models

Revision ID: 187bf39382a9
Revises: 16b130af7813
Create Date: 2023-06-05 09:34:19.626824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187bf39382a9'
down_revision = '16b130af7813'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
