"""Add roles

Revision ID: 8a77bd9a7112
Revises: b9030c13dd1b
Create Date: 2023-06-03 20:26:10.169461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a77bd9a7112'
down_revision = 'b9030c13dd1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
